# This file contains information about GUI crates and projects in the Rust
# ecosystem.
#
# The allowed keys are as follows:
#
# # A crate on crates.io.
# [crate.my-crate]
# # The name of the crate. Defaults to the crate name, but may be capitalized
# # or named differently if desired.
# name = "MyCrate"
# # Any tags/categories that may be relevant about the crate.
# tags = ["tag1", "tag2"]
# # A description of the crate. Defaults to the description on crates.io.
# description = "A crate to do stuff"
# # Location of the crate's code repository.
# #
# # Defaults to what is specified on crates.io.
# repo = "https://domain.invalid/mycrate/git"
# # Location of the crate's documentation.
# #
# # Defaults to what is specified on crates.io, or otherwise to docs.rs.
# docs = "https://domain.invalid/mycrate/docs"

[crate.webrender]
name = "WebRender"
tags = [
  "webrender",
]

[crate.masonry]
tags = []

[crate.rifs]
name = "Rust-In-Flutter"
tags = [
  "bindings",
  "flutter",
  "native",
  "cross-platform",
]

[crate.tinyfiledialogs]
tags = ["bindings", "tooling"]
