# This file contains information about GUI crates and projects in the Rust
# ecosystem.
#
# The allowed keys are as follows:
#
# # A crate on crates.io.
# [crate.my-crate]
# # The name of the crate. Defaults to the crate name, but may be capitalized
# # or named differently if desired.
# name = "MyCrate"
# # Any tags/categories that may be relevant about the crate.
# tags = ["tag1", "tag2"]
# # A description of the crate. Defaults to the description on crates.io.
# description = "A crate to do stuff"
# # Location of the crate's code repository.
# #
# # Defaults to what is specified on crates.io.
# repo = "https://domain.invalid/mycrate/git"
# # Location of the crate's documentation.
# #
# # Defaults to what is specified on crates.io, or otherwise to docs.rs.
# docs = "https://domain.invalid/mycrate/docs"

[crate.dioxus]
name = "Dioxus"
description = "Elegant React-like library for building user interfaces for desktop, web, mobile, SSR, liveview, and more."

[crate.slint]
name = "Slint"
description = "Slint is a toolkit to efficiently develop fluid graphical user interfaces for any display: embedded devices and desktop applications. It comes with a fast OpenGL renderer, a designer-friendly markup language and is written in Rust. Triple-licensed: GPLv3, Royalty-free, and Commercial."
tags = [
  "proc-macro",
  "winit",
  "embedded",
  "macos",
]

[crate.tauri]
name = "Tauri"
description = "Tauri is a framework for building tiny, blazing fast binaries for all major desktop platforms."
docs = "https://tauri.studio/en/"
tags = [
  "html",
  "macos",
  "gtk",
]

[crate.webrender]
name = "WebRender"
tags = [
  "webrender",
]

[crate.masonry]
tags = []

[crate.rifs]
name = "Rust-In-Flutter"
tags = [
  "bindings",
  "flutter",
  "native",
  "cross-platform",
]

[crate.tinyfiledialogs]
tags = ["bindings", "tooling"]
